import { Hostel, University, Review } from '../types';
import type { IconName } from '../components/neo/Icon';

// NOTE: `is_featured` marks the admin-chosen university that is pinned to the
// top of every university dropdown. For now UDSM (the most popular) is featured;
// an admin can move the flag to any other row later.
export const MOCK_UNIVERSITIES: University[] = [
  { id: '1', name: 'University of Dar es Salaam', short_name: 'UDSM', city: 'Dar es Salaam', latitude: -6.7714, longitude: 39.2226, student_count: 1847, is_featured: true },
  { id: '2', name: 'Ardhi University', short_name: 'ARU', city: 'Dar es Salaam', latitude: -6.7741, longitude: 39.2094, student_count: 640 },
  { id: '3', name: 'Muhimbili University of Health and Allied Sciences', short_name: 'MUHAS', city: 'Dar es Salaam', latitude: -6.8003, longitude: 39.2056, student_count: 512 },
  { id: '4', name: 'College of Engineering and Technology (CoET - UDSM)', short_name: 'CoET', city: 'Dar es Salaam', latitude: -6.7700, longitude: 39.2300, student_count: 388 },
  { id: '5', name: 'St. Augustine University of Tanzania', short_name: 'SAUT', city: 'Mwanza', latitude: -2.5148, longitude: 32.9010, student_count: 430 },
  { id: '6', name: 'Sokoine University of Agriculture', short_name: 'SUA', city: 'Morogoro', latitude: -6.8439, longitude: 37.6445, student_count: 505 },
  { id: '7', name: 'University of Dodoma', short_name: 'UDOM', city: 'Dodoma', latitude: -6.1630, longitude: 35.7516, student_count: 720 },
  { id: '8', name: 'Nelson Mandela African Institution of Science and Technology', short_name: 'NM-AIST', city: 'Arusha', latitude: -3.3731, longitude: 36.8260, student_count: 210 },
  { id: '9', name: 'Mzumbe University', short_name: 'MU', city: 'Morogoro', latitude: -6.8500, longitude: 37.6600, student_count: 360 },
  { id: '10', name: 'Institute of Finance Management', short_name: 'IFM', city: 'Dar es Salaam', latitude: -6.8100, longitude: 39.2900, student_count: 295 },
  { id: '11', name: 'Open University of Tanzania', short_name: 'OUT', city: 'Dar es Salaam', latitude: -6.8200, longitude: 39.2200, student_count: 480 },
  { id: '12', name: 'Kilimanjaro Christian Medical University College', short_name: 'KCMUCo', city: 'Moshi', latitude: -3.3600, longitude: 37.3400, student_count: 175 },
];

export const MOCK_HOSTELS: Hostel[] = [
  {
    id: '1', owner_id: 'owner1',
    name: 'Blue Horizon Hostel',
    description: 'Modern student hostel with premium amenities, high-speed WiFi, and a vibrant community atmosphere. Located just 5 minutes walk from the UDSM main gate. Our 24/7 security team and CCTV coverage ensures your safety at all times. We have dedicated study rooms, a communal kitchen, and regular social events to help you connect with fellow students.',
    address: 'Mlimani Road, Ubungo', city: 'Dar es Salaam',
    latitude: -6.7750, longitude: 39.2280,
    price_per_month: 180000, type: 'hostel', gender_preference: 'mixed',
    university_id: '1',
    images: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
    ],
    amenities: ['WiFi', 'Security', 'Water', 'Parking', 'Study Room', 'Laundry'],
    available_rooms: 8, total_rooms: 20,
    rating: 4.7, review_count: 124,
    distance: 0.5, is_verified: true,
    whatsapp: '+255712345678',
    created_at: new Date().toISOString(),
  },
  {
    id: '2', owner_id: 'owner2',
    name: 'Campus View Residence',
    description: 'Premium fully-furnished rooms with stunning campus views. All-inclusive pricing covers water, electricity, high-speed WiFi, and gym access. Our professional management team is available 24/7 to assist residents. Perfect for postgraduate students and those seeking a quiet study environment.',
    address: 'University Road, Kinondoni', city: 'Dar es Salaam',
    latitude: -6.7680, longitude: 39.2200,
    price_per_month: 250000, type: 'private_room', gender_preference: 'mixed',
    university_id: '1',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80',
    ],
    amenities: ['WiFi', 'Gym', 'Cafeteria', 'Security', 'AC', 'Furnished', 'Water'],
    available_rooms: 3, total_rooms: 15,
    rating: 4.9, review_count: 89,
    distance: 0.3, is_verified: true,
    whatsapp: '+255787654321',
    created_at: new Date().toISOString(),
  },
  {
    id: '3', owner_id: 'owner3',
    name: 'Sunset Student Lodge',
    description: 'Affordable quality accommodation for budget-conscious students. Clean, safe, and well-managed with reliable water supply and security. Shared rooms available at very competitive prices. Just 15 minutes by daladala to UDSM main campus.',
    address: 'Sinza Road, Kinondoni', city: 'Dar es Salaam',
    latitude: -6.7820, longitude: 39.2350,
    price_per_month: 120000, type: 'shared_room', gender_preference: 'male',
    university_id: '2',
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80',
    ],
    amenities: ['WiFi', 'Security', 'Water', 'Parking'],
    available_rooms: 12, total_rooms: 30,
    rating: 4.2, review_count: 67,
    distance: 1.2, is_verified: true,
    whatsapp: '+255755123456',
    created_at: new Date().toISOString(),
  },
  {
    id: '4', owner_id: 'owner4',
    name: 'Pearl Ladies Hostel',
    description: 'Safe and secure ladies-only hostel with CCTV throughout the compound, gated entrance, and a female warden on duty 24/7. Purpose-built for female students with well-lit corridors, clean shared bathrooms, and a dedicated study lounge. Walking distance from Muhimbili University.',
    address: 'Magomeni Road, Kinondoni', city: 'Dar es Salaam',
    latitude: -6.7900, longitude: 39.2180,
    price_per_month: 150000, type: 'hostel', gender_preference: 'female',
    university_id: '3',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
      'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=800&q=80',
    ],
    amenities: ['WiFi', 'Security', 'CCTV', 'Water', 'Study Room', 'Kitchen', 'Laundry'],
    available_rooms: 5, total_rooms: 25,
    rating: 4.8, review_count: 203,
    distance: 0.8, is_verified: true,
    whatsapp: '+255765432109',
    created_at: new Date().toISOString(),
  },
  {
    id: '5', owner_id: 'owner5',
    name: 'Elite Student Apartments',
    description: 'Luxury self-contained apartments for students who want privacy and comfort. Each unit features a private bathroom, kitchenette, living area, and balcony. Access to rooftop gym, swimming pool, and high-speed fiber internet. Premium living at its finest.',
    address: 'Msasani Peninsula', city: 'Dar es Salaam',
    latitude: -6.7560, longitude: 39.2560,
    price_per_month: 450000, type: 'apartment', gender_preference: 'mixed',
    university_id: '1',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    ],
    amenities: ['WiFi', 'AC', 'Kitchen', 'Gym', 'Pool', 'Security', 'Parking', 'Furnished'],
    available_rooms: 2, total_rooms: 10,
    rating: 5.0, review_count: 45,
    distance: 2.1, is_verified: true,
    whatsapp: '+255700111222',
    created_at: new Date().toISOString(),
  },
  {
    id: '6', owner_id: 'owner6',
    name: 'Karibu Budget Hostel',
    description: 'Friendly budget-friendly hostel for students who want value for money. Clean dormitory-style rooms with secure storage lockers, communal bathrooms, and a shared kitchen. Close to public transport and local markets.',
    address: 'Buguruni Road, Ilala', city: 'Dar es Salaam',
    latitude: -6.8100, longitude: 39.2100,
    price_per_month: 90000, type: 'hostel', gender_preference: 'mixed',
    university_id: '1',
    images: [
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80',
    ],
    amenities: ['WiFi', 'Security', 'Water'],
    available_rooms: 15, total_rooms: 40,
    rating: 3.9, review_count: 312,
    distance: 1.8, is_verified: false,
    whatsapp: '+255744555666',
    created_at: new Date().toISOString(),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: '1', hostel_id: '1', user_id: 'u1', rating: 5,
    comment: 'Amazing place! The WiFi is super fast and the security is excellent. The study room saved my semester. Would definitely recommend to any student looking for quality accommodation near UDSM.',
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    user: { id: 'u1', full_name: 'Amina Hassan', email: 'amina@udsm.ac.tz', created_at: '' },
  },
  {
    id: '2', hostel_id: '1', user_id: 'u2', rating: 4,
    comment: 'Good hostel overall. Clean rooms and friendly staff. Water supply is reliable which is a big plus. The study room could use more desks during exam period.',
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    user: { id: 'u2', full_name: 'John Mwangi', email: 'john@udsm.ac.tz', created_at: '' },
  },
  {
    id: '3', hostel_id: '1', user_id: 'u3', rating: 5,
    comment: 'Best hostel in Ubungo! The management is very responsive and the community feel is great. Made lifelong friends here. Great value for the price.',
    created_at: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    user: { id: 'u3', full_name: 'Fatuma Salim', email: 'fatuma@udsm.ac.tz', created_at: '' },
  },
];

export const AMENITY_ICONS: Record<string, IconName> = {
  'WiFi': 'wifi',
  'Security': 'shield-checkmark',
  'CCTV': 'videocam',
  'Water': 'faucet',
  'Parking': 'parking',
  'AC': 'air-conditioner',
  'Gym': 'gym',
  'Pool': 'swimming-pool',
  'Kitchen': 'utensils',
  'Cafeteria': 'coffee',
  'Furnished': 'couch',
  'Laundry': 'washer',
  'Study Room': 'book',
};
